### ISSUE TITLE
appropriate argument setting?

### ISSUE THREAD

**Issue by zwx8981** [airsplay/R2R-EnvDrop#1]
Hi, thank you for sharing the code. Could you please show all necessary arguments setting (for reproduction of paper results) ?

**Comment by airsplay** [comment]
Hi, I am now testing the code with the latest PyTorch 1.1 because PyTorch 0.4.X (which is the PyTorch version when I developed this code) has a lot of numerical issues. For example,  [multinomial distribution would sample entries with prob 0](https://github.com/pytorch/pytorch/pull/9960), which is solved in version 1.0. Thus, I do not want anyone else struggling with handling these annoying issues.

I am aiming to release the full code before NAACL 2019 (06/03).

**Comment by zwx8981** [comment]
OK，than you very much~
