### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by billhhh** [airsplay/R2R-EnvDrop#12]
Thank you for sharing your great work!

I am reading your codes now, but I found some weird parts. They are probably bugs while I am not sure as well. Please point me out if I am wrong

1. https://github.com/airsplay/R2R-EnvDrop/blob/master/r2r_src/agent.py#L184, cannot find matched "if" to this "else".

2. https://github.com/airsplay/R2R-EnvDrop/blob/master/r2r_src/agent.py#L570, five return values which do not match the function definitions here.

**Comment by airsplay** [comment]
Thanks for your interest :). 

1. It's a statement in Python called for-else; Please see [here](https://book.pythontips.com/en/latest/for_-_else.html) for the usage.

2. It is related to the beam search results. However, the beam search has some unknown problem because I clean the code a little bit. Thus I did not go into these functions but publish the code as a preview. The correct beam-search results and code are available [here](https://github.com/airsplay/R2R-EnvDrop/issues/11). I aim to locate/fix it soon and release a new version with beam-search. 

Best,
Hao

**Comment by billhhh** [comment]
Thank you for your reply!
