### ISSUE TITLE
Test Question

### ISSUE THREAD

**Issue by jingquanliang** [airsplay/R2R-EnvDrop#16]
After I train the model， i use the test environment to evaulate，the success rate result is below， i dont understand why the result is so low？ please help me， is there something wrong when i test ？
![image](https://user-images.githubusercontent.com/8544622/74718546-69e8d180-526d-11ea-9751-65073a0a21bd.png)
the test script is：
name=agent
flag="--train validlistener --featdropout 0.3 --angleFeatSize 128
      --feedback argmax
      --mlWeight 0.2
      --subout max --dropout 0.5 --optim rms --lr 1e-4 --iters 80000 --submit"
CUDA_VISIBLE_DEVICES=$1 python r2r_src/train.py $flag --name $name

**Comment by airsplay** [comment]
Thanks. 

It is because the test data does not provide the ground truth label. It only gives the start viewpoint so the accuracy is actually the frequency of [final-viewpoint == start-viewpoint].

To get the test results, please use the testing servers here https://evalai.cloudcv.org/web/challenges/challenge-page/97/overview. However, there is a limitation of 5 trails.

**Comment by jingquanliang** [comment]
> Thanks.
> 
> It is because the test data does not provide the ground truth label. It only gives the start viewpoint so the accuracy is actually the frequency of [final-viewpoint == start-viewpoint].
> 
> To get the test results, please use the testing servers here https://evalai.cloudcv.org/web/challenges/challenge-page/97/overview. However, there is a limitation of 5 trails.

thank u very much for your reply, I appreicate u work
